# Extra: selection of TF-IDF components based on entropy

This notebook is a small extension of the original project. Here we want to further analyze the network built using tf-idf embeddings of abstracts. In particular, since tf-idf embedding vectors have a huge number of components, we want to see if filtering some of these components can lead to a reduction of the noise present in the embedding vectors, and thus bring to an improvement of classification performances.

The selection of components is based on entropy: for each component of the vector embeddings, the information entropy is calculated across all papers is calculated using:

\begin{equation}
    H = -\sum_{i=1}^N p_ilog(p_i)
\end{equation}

where $N = 25877$ is the total number of papers, while $p_i$ represents the value of a certain component of embedding vectors in paper $i$ when the values of that component are normalized across all papers so that $\sum_{i=1}^N p_i = 1$.

After calculating the value of entropy for all embedding components, only the components with entropy higher than a certain threshold are kept. Finally, the distance matrix, the adjacency matrix and the corresponding network are built from tf-idf embeddings filtered in this way, and all the algorithms already employed in the original project are tried to divide the network into communities, to see if we have an improvement of classification after the selection of components.

## Entropy calculation

First of all we want to compute the entropy of all components of embedding vectors, and save in a npz file the array containing all values of entropy.

In [8]:
from components_selection import entropy_component
from scipy.sparse import load_npz, save_npz
import numpy as np
import pandas as pd
import networkx as nx
import subprocess
import pickle
from collections import Counter

In [2]:
tf_idf_embeddings = load_npz("../embeddings/abstract_embeddings_tfidf.npz")

In [ ]:
for i in range(223):
    #select 250 columns, since 223 * 250 = 55750, number of columns of the original matrix
    batch_of_columns = tf_idf_embeddings[:, (i * 250):((i+1) * 250)].toarray()

    entropy = entropy_component(batch_of_columns)

    #append the arrays obtained in the different cycles
    if i == 0:
        full_entropy_array = entropy
    else:
        full_entropy_array = np.concatenate((full_entropy_array, entropy))

#save the array in the npz format
np.savez("./entropy_array.npz", full_entropy_array)

/home/riccardo/uni_projects/complex_networks/Abstract_network/extra/components_selection.py:32: RuntimeWarning: divide by zero encountered in log
  embedding_matrix_normalized = np.where(np.isclose(embedding_matrix_normalized, 0.), 0., (embedding_matrix_normalized * np.log(embedding_matrix_normalized)) * (-1))
/home/riccardo/uni_projects/complex_networks/Abstract_network/extra/components_selection.py:32: RuntimeWarning: invalid value encountered in multiply
  embedding_matrix_normalized = np.where(np.isclose(embedding_matrix_normalized, 0.), 0., (embedding_matrix_normalized * np.log(embedding_matrix_normalized)) * (-1))

Now load the array with entropies, and filter the components of the tf-idf embeddings keeping only those with entropy greater than 1 (this threshold on entropy is selected arbitrarily, later we will see how different values of threshold influence the structure of the resulting network).

In [3]:
entropy_array = np.load("./entropy_array.npz")['arr_0']

In [9]:
print(np.max(entropy_array))
print(np.min(entropy_array))

10.028510818552421
0.0

As a first analysis, we can print the maximum and minimum values of entropy of the embedding components: as we expect, the minimum value of entropy is 0: this happens when the component is different from 0 only in one paper (so it is a word that appears only in a certain paper).

## Build network

Now we can build the distance matrix, the adjacency matrix, the relative network using the same functions we used for the network with all the components.

Using always the threshold distance of 0.2, we try different values of threshold entropy to filter the components of the embeddings. In particular, we use ten different thresholds in the range 1-8 (the range is selected considering the minimum and maximum value of entropy).

In [1]:
from components_selection import sweep_entropy_threshold

sweep_entropy_threshold()

Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration

In [4]:
pd.read_csv("./results/connected_components_entropy.csv")

,Unnamed: 0,Threshold,Embedding_components,Connected_components,Largest_component
0,0,0.5,25421.0,25686.0,3.0
1,1,1.0,32761.0,20570.0,18.0
2,2,1.5,38262.0,13030.0,7952.0
3,3,2.0,42100.0,7602.0,17378.0
4,4,2.5,45040.0,4603.0,20970.0
5,5,3.0,47281.0,2845.0,22881.0
6,6,3.5,49138.0,1975.0,23807.0
7,7,4.0,50686.0,1713.0,24072.0
8,8,4.5,51960.0,1823.0,23944.0
9,9,5.0,53013.0,2053.0,23708.0

We use a threshold of 2.5 (so that we eliminate almost 10000 components, so almost 20% of the total components),and we try different values of threshold on distance to find the best one.

In [6]:
from components_selection import sweep_connected_components

filtered_embeddings = tf_idf_embeddings[:, np.where(entropy_array < 2.5)[0]]
sweep_connected_components(embedding_matrix = filtered_embeddings)

Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration

In [7]:
pd.read_csv("./results/connected_components.csv")

   Unnamed: 0  Threshold  Connected_components  Largest_component
0           0   0.100000                2979.0            22860.0
1           1   0.144444                3448.0            22334.0
2           2   0.188889                4292.0            21331.0
3           3   0.233333                5542.0            19776.0
4           4   0.277778                7259.0            17251.0
5           5   0.322222                9337.0            13735.0
6           6   0.366667               11600.0             8741.0
7           7   0.411111               13976.0             2517.0
8           8   0.455556               15948.0              132.0
9           9   0.500000               17698.0               52.0

We use a threshold of 0.05: the similarity between papers decreases if we remove the components with higher entropy, so we need to use a lower distance threshold in order to have a giant component big enough in the network.

In [10]:
from components_selection import build_adjacency_matrix

#filter embeddings and build the relative adjacency matrix
filtered_embeddings = tf_idf_embeddings[:, np.where(entropy_array < 2.5)[0]]
print("Number of remaining components: " + str(filtered_embeddings.shape[1]))
adjacency_matrix = build_adjacency_matrix(filtered_embeddings, threshold = 0.05)

#save the adjacency matrix
save_npz("./results/filtered_adjacency_matrix.npz", adjacency_matrix.tocsr())

#build the network corresponding to the adjacency matrix, and count the number of links, the number of connected components
#and the largest connected component
G = nx.from_scipy_sparse_array(adjacency_matrix)
print("Number of links: " + str(G.size()))
print("Number of connected components: " + str(nx.number_connected_components(G)))
print("Size of the largest connected component: " + str(max([len(c) for c in list(nx.connected_components(G))])))

Number of remaining components: 45040
Number of links: 185128
Number of connected components: 2769
Size of the largest connected component: 23084

The network built using tf-idf embeddings filtered by entropy has almost half of the links of the same network built without filtering on entropy: probably a lower number of links means an easier division of the network into communities.

## Division into communities

Before using the algorithms to divide the network into communities, we build the matrix of connections between cathegories, and then for each cathegory we find the group of papers with the highest number of connections with papers of that cathegory.

In [11]:
from components_selection import connectivity_between_cathegories

connectivity_between_cathegories()

Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration

In [12]:
subprocess.run(["Rscript", "./max_connected_cathegory.R"])
pd.read_csv("./results/max_connected_cathegory.csv")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
New names:
• `` -> `...1`
Rows: 22 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): ...1
dbl (23): Accelerator Physics, Applied Physics, Atmospheric and Oceanic Phys...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

,Cathegory,Max_connected_cathegory,Connections
0,Accelerator Physics,Accelerator Physics,668
1,Applied Physics,Optics,3344
2,Atmospheric and Oceanic Physics,Atmospheric and Oceanic Physics,1724
3,Atomic and Molecular Clusters,Chemical Physics,149
4,Atomic Physics,Atomic Physics,1795
5,Biological Physics,Biological Physics,2644
6,Chemical Physics,Chemical Physics,4773
7,Classical Physics,Optics,397
8,Computational Physics,Computational Physics,2312
9,"Data Analysis, Statistics and Probability",Physics and Society,631
10,Fluid Dynamics,Fluid Dynamics,6971
11,General Physics,General Physics,238
12,Geophysics,Geophysics,1231
13,History and Philosophy of Physics,History and Philosophy of Physics,604
14,Instrumentation and Detectors,Instrumentation and Detectors,3980
15,Medical Physics,Medical Physics,2980
16,Optics,Optics,9846
17,Physics and Society,Physics and Society,5718
18,Physics Education,Physics Education,822
19,Plasma Physics,Plasma Physics,2850
20,Popular Physics,Physics and Society,122
21,Space Physics,Space Physics,779

Using a filter on entropy does not change so much the connections between cathegories: the majority of cathegories is still connected mostly with papers of the same cathegory.

Now we can use the three algorithms to divide the network into communities.

In [1]:
from components_selection import split_fiedler_eigenvector, split_k_means, split_louvain_method

split_fiedler_eigenvector()
split_k_means()
split_louvain_method()

Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration
Iteration

We can calculate the number of papers in each one of the communities in which the network has been divided by the three algorithms.

In [ ]:
from components_selection import table_of_papers_by_community, table_of_papers_by_community_louvain

table_of_papers_by_community()
table_of_papers_by_community_louvain()

In [4]:
pd.read_csv("./results/papers_by_community_fiedler_kmeans.csv")

    Unnamed: 0  Fiedler  K_Means
0            0      231    23036
1            1      337        4
2            2      300        2
3            3      300        2
4            4      350        2
5            5      317        3
6            6      317        2
7            7      303        2
8            8      293        3
9            9      424        2
10          10      446        2
11          11      385        2
12          12      344        3
13          13      435        3
14          14      441        2
15          15     6141        2
16          16      369        2
17          17      386        2
18          18      443        2
19          19      273        2
20          20      289        2
21          21     9960        2

In [6]:
pd.read_csv("./results/papers_by_community_louvain.csv")

    Unnamed: 0  Louvain
0            0      427
1            1      733
2            2      339
3            3      416
4            4      458
5            5      215
6            6      407
7            7      279
8            8      404
9            9      147
10          10     2781
11          11      177
12          12     1053
13          13      619
14          14      314
15          15      324
16          16     1014
17          17      260
18          18      268
19          19      151
20          20      425
21          21      335
22          22      498
23          23      353
24          24      259
25          25      279
26          26      433
27          27      643
28          28      384
29          29      459
30          30      421
31          31      152
32          32      298
33          33      418
34          34      447
35          35      372
36          36      312
37          37      873
38          38      238
39          39      248
40          40      418
41          41      251
42          42      309
43          43      407
44          44      486
45          45      557
46          46      406
47          47      279
48          48      643
49          49      695

There are clearly some important differences with respect to the communities obtained using the non-filtered embeddings. While the K-Means approach still performs very badly, the Fiedler method is able to split the network into communities with a more similar number of nodes in each community. Now we have two communities with the vast majority of nodes instead of 1, and even the other communities have a consistent number of nodes. At the same time, the Louvain algorithm divides the network into 49 communities instead of 19, with a similar number of nodes in each community.

These differences with the case of the network built using non-filtered component is due to the lower number of links: filtering the embedding components with higher entropy reduces the similarity between papers, and so the number of links in the network is lower. This means that the network is more easily separable, and so we obtain more communities, each one with a consistent number of nodes.

If we had kept instead the components with higher entropy, we wuold have obtained the opposite result: the higher entropy components are those corresponding to the words that appear in a bigger number of papers, so removing low entropy components would have made each paper more similar to the others, and thus it would have increased the number of links in the network, making the division into communities much more difficult (and more computationally demanding, too).

Finally, we want to inspect the number of papers of each cathegory in each community. This can be done by looking at the csv files "cathegories_by_community", which are created by the following cell

In [ ]:
from components_selection import cathegories_by_community

cathegories_by_community(split_method = 'fiedler')
cathegories_by_community(split_method = 'kmeans')
cathegories_by_community(split_method = 'louvain')

or directly by using the two following cells to select a community (obtained using respectively Fiedler and Louvain methods) and see the number of papers of each cathegory in that community

In [16]:
#use this cell to see the number of papers of each cathegory in each community (obtained using the Fiedler method)
with open("./results/fiedler_split", "rb") as file:
    subgraphs_list = pickle.load(file)

#use this variable to select the number of the community to consider
community = 5

topics_of_community = nx.get_node_attributes(subgraphs_list[community], "Topic")
number_of_papers_per_topic = dict(Counter(list(topics_of_community.values())))

number_of_papers_per_topic

{'Fluid Dynamics': 29,
 'Atmospheric and Oceanic Physics': 11,
 'Computational Physics': 40,
 'Atomic Physics': 19,
 'Instrumentation and Detectors': 4,
 'Applied Physics': 27,
 'Optics': 87,
 'Physics and Society': 25,
 'History and Philosophy of Physics': 4,
 'Chemical Physics': 18,
 'Classical Physics': 7,
 'Plasma Physics': 7,
 'General Physics': 7,
 'Biological Physics': 11,
 'Data Analysis, Statistics and Probability': 4,
 'Space Physics': 1,
 'Medical Physics': 5,
 'Accelerator Physics': 5,
 'Geophysics': 4,
 'Popular Physics': 2}

In [27]:
#use this cell to see the number of papers of each cathegory in each community (obtained using the Louvain method)
with open("./results/louvain_split", "rb") as file:
    subgraphs_list = pickle.load(file)

#use this variable to select the number of the community to consider
community = 13

topics_of_community = nx.get_node_attributes(subgraphs_list[community], "Topic")
number_of_papers_per_topic = dict(Counter(list(topics_of_community.values())))

number_of_papers_per_topic

{'Optics': 83,
 'Applied Physics': 39,
 'Computational Physics': 73,
 'Classical Physics': 16,
 'General Physics': 24,
 'Plasma Physics': 111,
 'Atomic Physics': 24,
 'Space Physics': 53,
 'Atomic and Molecular Clusters': 4,
 'Chemical Physics': 35,
 'Medical Physics': 10,
 'Fluid Dynamics': 59,
 'Data Analysis, Statistics and Probability': 17,
 'Instrumentation and Detectors': 15,
 'Geophysics': 8,
 'Physics and Society': 10,
 'History and Philosophy of Physics': 9,
 'Biological Physics': 11,
 'Physics Education': 3,
 'Atmospheric and Oceanic Physics': 10,
 'Accelerator Physics': 4,
 'Popular Physics': 1}

Moreover, the two following cells can be used to see the titles of the papers belonging to a certain community

In [18]:
#use this cell to see the titles of the papers of in each community (obtained using the Fiedler method)
with open("./results/fiedler_split", "rb") as file:
    subgraphs_list = pickle.load(file)

#use this variable to select the number of the community to consider
community = 5

titles_of_community = list(nx.get_node_attributes(subgraphs_list[community], "Title").values())

titles_of_community

['Geometry-driven jets underlie dispersal of plants and fungi by raindrops',
 'A Model Intercomparison Study of Mixed-Phase Clouds in a Laboratory Chamber',
 'Energy-Efficient Sampling Using Stochastic Magnetic Tunnel Junctions',
 'Attosecond transient absorption spectroscopy in monolayer hexagonal boron nitride',
 'Sum-of-Gaussians tensor neural networks for high-dimensional Schr\\"odinger equation',
 'Virtual Sensing for Solder Layer Degradation and Temperature Monitoring in IGBT Modules',
 'Permanently magnetized axion-photon conversion surface for direct dark matter searches with BRASS-p',
 'Magnetoresistance effect based on spin-selective transport in nanodevices using chiral molecules',
 'Hidden quantum-classical correspondence in chaotic billiards revealed by mutual information',
 'Coupling opinion dynamics and epidemiology',
 'Wave turbulence, thermalization and multimode locking in optical fibers',
 'Spontaneous symmetry breaking in nonlinear superradiance',
 'Local Wigner-Mass Maps and Integrated Negativity as Measures of nonclassicality in Quantum Chaotic Billiards',
 'Superconductivity and a van Hove singularity confined to the surface of a topological semimetal',
 'Quantum Inaccessibility',
 'British Automobiles, Aging Theory, and the Death of Complex Machines',
 'Antiferromagnetic diamond network as an efficient spin filter: Proposition of a spin-specific semi-conducting behavior',
 'Vortices, turbulence, and center of pressure in flow over pitching swept wings',
 "LaPON: A Lagrange's-mean-value-theorem-inspired operator network for solving PDEs and its application on NSE",
 'Combined Light Excitation and Scanning Gate Microscopy on Heterostructure Nanowire Photovoltaic Devices',
 'Mie-tronics supermodes and symmetry breaking in nonlocal metasurfaces',
 'The Role and Mechanism of Deep Statistical Machine Learning In Biological Target Screening and Immune Microenvironment Regulation of Asthma',
 'The life cycle of scientific principles -- a template for characterizing physical principles',
 'Connected components in networks with higher-order interactions',
 'Poncelet property of planar elliptic integrable Kepler billiards',
 'Data Assimilation in Large Eddy Simulation: Addressing Model-Observation Mismatch from Navier-Stokes Data',
 'Cross-scale Interaction between Microturbulence and Fishbone in Fusion Plasmas',
 'Topological Regularization of 1 Loop and 2 Loop Gravitational Corrections in the Higgs Fermion Sector',
 'Programmable Focal Elongation and Shaping of High-Intensity Laser Pulses using Adaptive Optics',
 'Deep-learning-enabled inverse design of large-scale metasurfaces with full-wave accuracy',
 'Universal in-line waveform characterization using arbitrary non-linear responses',
 'Reversible Imprinting and Retrieval of Quantum Information: Experimental Verification of the Quantum Memory Matrix Hypothesis',
 'Quantum statistics of single-mode radiation emitted by superradiant Dicke states',
 "Modal analysis of a domain decomposition method for Maxwell's equations in a waveguide",
 'Quantifying hydrogen bonding using electrically tunable nanoconfined water',
 'Electron Orbital Angular Momentum Polarization in Neutral Atoms',
 'A coupled HDG discretization for the interaction between acoustic and elastic waves',
 'Defining and classifying models of groups: The social ontology of higher-order networks',
 'Terahertz Chip-Scale Meta-Networks with LSPR Routing: A Theoretical Framework',
 'asKAN: Active Subspace embedded Kolmogorov-Arnold Network',
 'Update hydrological states or meteorological forcings? Comparing data assimilation methods for differentiable hydrologic models',
 'Non-Hermitian funneling in anisotropic media',
 'Topologically Protected Polaritonic Bound State in the Continuum',
 'Bell Correlations from Prepared Coherence in Entangled Dirac Wavepackets',
 'Encounter Times of Intermittently Running Particles',
 'Contemporary Perspectivism as a Framework of Scientific Inquiry in Quantum Mechanics and Beyond',
 'Electrified EHL line contact with dielectric breakdown of lubricant -- a numerical model',
 'Topological Relics of Infrared QED in the Rayleigh-Jeans Regime',
 'Beyond Resolution: Multi-Scale Weather and Climate Data for Alpine Renewable Energy in the Digital Twin Era -- First Evaluations and Recommendations',
 'Orbit Elements from Kepler Solutions in Projective Coordinates',
 'Hamiltonian model for energy condensation in classical systems: Relevance to proteins',
 'Influence of ion motion in a resonantly driven wakefield accelerator',
 'Blue-shifted dispersive waves and broadband UV emission using dual-core SiN waveguides',
 'High-order Nodal Space-time Flux Reconstruction Methods for Hyperbolic Conservation Laws on Curvilinear Moving Grids',
 'Unveiling prethermalization and thermal processes through the simplest one-dimensional topological model',
 'GridFF: Efficient Simulation of Organic Molecules on Rigid Substrates',
 'Topological cluster synchronization via Dirac spectral programming on directed hypergraphs',
 'On the First Quantum Correction to the Second Virial Coefficient of a Generalized Lennard-Jones Fluid',
 'Low-loss far-infrared surface phonon polaritons in suspended SrTiO3 nanomembranes',
 'Ultrafast Coherent Bandgap Modulation Probed by Parametric Nonlinear Optics',
 'Two-Phase Boiling in a Replaceable Embedded Heat Sink for Ultra-High Heat Flux SiC Chip Cooling',
 'Obstacle-tuned transition from chaotic to coherent vortex flows and odd diffusion in chiral active fluids',
 'Dynamics of Ideal Fluid Flows',
 'Optimizing confidence in negative-partial-transpose-based entanglement criteria',
 'The study of coherent Rayleigh-Brillouin scattering in multiple flow regimes using unified gas-kinetic scheme',
 'Structure and dynamics jointly stabilize the international trade hypergraph',
 'Stealthy-Hyperuniform Wave Dynamics in Two-Dimensional Photonic Crystals',
 'Forcing mass transfer approach in multicomponent miscible mixtures using the lattice Boltzmann method',
 'Phase evolution of strong-field ionization',
 'An Ultra-Low Power and Fast Ising Machine using Voltage-Controlled Magnetoresistive Random Access Memory',
 'Surface plasmons in metamaterial cavities: Scattering by obstacles with negative wave speed',
 'Classifying Complex Dynamical and Stochastic Systems via Physics-Based Recurrence Features',
 'Origin of compact exoplanetary systems during disk infall',
 'Introduction to the symplectic group Sp(2)',
 'AI Data Centers Need Pioneers to Deliver Scalable Power via Offgrid AI',
 'Localized surface plasmons in a Weyl semimetal nanosphere',
 'Topology of the near field in enhanced transmission through subwavelength apertures',
 'Global Forecasting of Tropical Cyclone Intensity Using Neural Weather Models',
 'A scalable advantage in multi-photon quantum machine learning',
 'Design Optimized CMOS Compatible Hybrid Silicon MIM Waveguide Cavity for Label Free Sensing',
 'Seal Whisker-Inspired Sensor for Amplifying Wake-Induced Vibrations in Underwater Marine Animal Monitoring',
 'Strongly confined Mid-infrared to Terahertz Phonon Polaritons in Ultra-thin SrTiO3',
 'Three-Dimensional Rigid-Body Impact Mechanics for Automobile Collisions',
 'Bound excited states of Fr\\"ohlich polarons in one dimension',
 'Hyperedge Overlap drives Synchronizability of Systems with Higher-Order interactions',
 'DANRA: The Kilometer-Scale Danish Regional Atmospheric Reanalysis',
 'Monitoring Single DNA Docking Site Activity With Sequential Modes of an Optoplasmonic Whispering-Gallery Mode Biosensor',
 'Photonic bandgap properties of hyperuniform systems self-assembled in a microfluidic channel',
 'Transient thermo-elasto-hydrodynamic study of herringbone-grooved mechanical face seal during start-up stage',
 'On-chip wave chaos for photonic extreme learning',
 'Dual-Input Dynamic Convolution for Positron Range Correction in PET Image Reconstruction',
 'Observation of non-Hermitian many-body phase transition in a Rydberg-atom array',
 'Estimate of the exit time for the Long Range Ising model on random regular graphs',
 'Relations Among Different Inequality Measures in Complex Systems: From Kinetic Exchange to Earthquake Models',
 'Half-life determination of heavy ions in a storage ring considering feeding and depleting background processes',
 'Meta-heuristic Hypergraph-Assisted Robustness Optimization for Higher-order Complex Systems',
 'Electrically reconfigurable extended lasing state in an organic liquid-crystal microcavity',
 'Channel Ordering for Fairness in Elastic Optical Networks via a LLM-Guided Bottleneck TSP Solver',
 'An analysis of capital market through the lens of integral transforms: exploring efficient markets and information asymmetry',
 'Broad Spectral Tuning of Ultra-Low Loss Polaritons in a van der Waals Crystal by Intercalation',
 'Dynamical thermalization, Rayleigh-Jeans condensate, vortexes and wave collapse in quantum chaos fibers and fluid of light',
 'Forecasting Low-Dimensional Turbulence via Multi-Dimensional Hybrid Quantum Reservoir Computing',
 'Degrees of universality in wave turbulence',
 'Automated Quantum Chemistry Code Generation with the p$^\\dagger$q Package',
 'Mesoscale particle-based simulations of flow in expansion-contraction microchannels at low Reynolds number',
 'Tailoring spatial correlations with quantum interference',
 'Blowup of solutions for compressible viscoelastic fluid',
 'Extended-variable probabilistic computing with p-dits',
 'Symbolic Higher-Order Analysis of Multivariate Time Series',
 'Dual-Mode Asymmetric Transmission based on Asymmetric and Orthogonal Gratings: Polarization-Dependent and -Independent Modes',
 'Nanolaser and logic gates on carbon nanotubes',
 'On internal wave whispering gallery modes in channels and critical-slope wave attractors',
 'Modeling temporal hypergraphs',
 'A Virtual Fields Method-Genetic Algorithm (VFM-GA) calibration framework for isotropic hyperelastic constitutive models with application to an elastomeric foam material',
 'Proposal for the Application of Fractional Operators in Polynomial Regression Models to Enhance the Determination Coefficient $R^2$ on Unseen Data',
 'Anisotropic Dielectric Function of Graphite Probed by Far- and Near-Field Spectroscopies',
 'Improving the performance of optical inverse design of multilayer thin films using CNN-LSTM tandem neural networks',
 'Lieb-Mattis states for robust entangled differential phase sensing',
 'Practical protein-pocket hydration-site prediction for drug discovery on a quantum computer',
 'Unconventional localization of light with Mie-tronics',
 'A Pathway to Practical Quantum Advantage in Solving Navier-Stokes Equations',
 'Autodifferentiable Geometric Restraints for Enhanced Sampling Simulations with Classical and Machine Learned Force Fields',
 'Hybrid deep learning and iterative methods for accelerated solutions of viscous incompressible flow',
 'Using Label-Free Raman Spectroscopy Integrated with Microfluidic Chips to Probe Ferroptosis Networks in Cells',
 'FIGNN: Feature-Specific Interpretability for Graph Neural Network Surrogate Models',
 'Thermalization of quantum light induced by classical nonlinear wave dynamics',
 'Thermodynamics and Statistical Equilibrium of Large-Scale Hydroelastic Wave Turbulence',
 'Random batch sum-of-Gaussians algorithm for molecular dynamics simulations of Yukawa systems in three dimensions',
 'Clustering and emergent hyperuniformity by breaking microswimmer shape and actuation symmetries',
 'Radiosonde-constrained reconstructions reveal a weakening Northern Hadley circulation',
 'Two-Mode Bosonic State Tomography with Single-Shot Joint-Parity Measurement of a Trapped Ion',
 'MAUSAM: An Observations-focused assessment of Global AI Weather Prediction Models During the South Asian Monsoon',
 'Quasiparticle properties of long-range impurities in a Bose condensate',
 'Effect of Gd and Co content on electrochemical and electronic properties of La$_{1.5}$Mg$_{0.5}$Ni$_7$ alloys: a combined experimental and first-principles study',
 'Community detection in hypergraphs through hyperedge percolation',
 'Optical Waveguide-Pair Design for CMOS-Compatible Hybrid III-V-on-Silicon Quantum Dot Lasers',
 'SURGIN: SURrogate-guided Generative INversion for subsurface multiphase flow with quantified uncertainty',
 'Rigorous theory of coupled resonators',
 'A stochastic noise model based excess noise factor expressions for staircase avalanche photodiodes',
 'Analogue simulation of quantum gravity black hole models in a dc-SQUID array',
 'Full Polarization Control of Photons with Evanescent Wave Coupling in the Ultra Subwavelength Gap of Photonic Molecules',
 'Near-field-free super-potential FFT method for the three-dimensional free-space Poisson equation',
 'Optimal alignment of Lorentz orientation and generalization to matrix Lie groups',
 'Elliptic Relaxation Strategies to Support Numerical Stability of Segregated Continuous Adjoint Flow Solvers',
 'Four-channel Imaging Based on Reconfigurable Metasurfaces: Hyperchaotic Encryption under Physical Protection',
 'Preventing an Extractive Green Hydrogen Industry: Risks and Benefits of Grid Expansion and Green Hydrogen in and for Kenya',
 'Characterization of NbTi wires for the electron-ion collider project',
 'A Gaussian process approach for rapid evaluation of skin tension',
 'Formation of Cavity-Polaritons via High-Order Van Hove Singularities',
 'Hypergraph modelling of wave scattering to speed-up material design',
 'Normalized Ensemble-Averaged OAM Spectrum in Disordered Statistical Q-Plates',
 'Extended defects in hard disk system and melting criteria',
 'Enhanced interferometric resolution via N-fold intensity-product measurements without sacrificing phase sensitivity',
 'Characteristic boundary conditions for Hybridizable Discontinuous Galerkin methods',
 'Dual Affine Connections, Legendre Transforms, and Black Hole Thermodynamics',
 'One- and two-dimensional solitons under the action of the inverted cubic-quintic nonlinearity',
 'Predicting the Oscillatory Regimes of Global Synchrony Induced by Secondary Clusters',
 'Pattern Formation in Robotic Mechanical Metamaterial',
 'Effective and asymptotic scaling in a one-dimensional billiard problem',
 'Explosive adoption of corrupt behaviors in social systems with higher-order interactions',
 'Random Batch Sum-of-Gaussians Method for Molecular Dynamics of Born-Mayer-Huggins Systems',
 'Photonics of topological magnetic textures',
 'MeshODENet: A Graph-Informed Neural Ordinary Differential Equation Neural Network for Simulating Mesh-Based Physical Systems',
 'Scalable manufacturing of polarization-insensitive metalenses with high-uniform focal arrays in the visible',
 "Two-dimensional moir\\'{e} phonon polaritons",
 'Effect of Berry connection on attosecond transient absorption spectroscopy in gapped graphene',
 'Ultracompact high-Q whispering gallery mode microresonator in a non-closed waveguide path',
 'High-order Multiscale Preconditioner for Elasticity of Arbitrary Structures',
 'Hybrid Boundary Physics-Informed Neural Networks for Solving Navier-Stokes Equations with Complex Boundary',
 'Interplay between pitch control and top speed in soccer: The stamina factor',
 'Schr\\"odinger equation with Pauli-Fierz Hamiltonian and double well potential as model of vibrationally enhanced tunneling for proton transfer in hydrogen bond',
 'Explainable autoencoder for neutron star dense matter parameter estimation',
 'Turbulence modulation in particle-laden channel flow: the particle inertial effects',
 'Supporting Higher-Order Interactions in Practical Ising Machines',
 'Direct readout of excited state lifetimes in chlorin chromophores under electronic strong coupling',
 'Errors in quantum state identification with ultrashort pulses',
 'Effect of cohesion on the gravity-driven evacuation of metal powder through Triply-Periodic Minimal Surface structures',
 'Equalities and inequalities from entanglement, loss, and beam splitters',
 'High-accuracy low-noise electrical measurements in a closed-cycle pulse-tube cryostat',
 'Compact Plasmonic Logic Gates Enabled by Magnetoelectric Light Funneling for On-Chip Optical Computing in the Telecom Band',
 'A comparison of stretched-grid and limited-area modelling for data-driven regional weather forecasting',
 'Transformability reveals the interplay of dynamics across different network orders',
 'Model Training, Data Assimilation, and Forecast Experiments with a Hybrid Atmospheric Model that Incorporates Machine Learning',
 'Obvious and non-obvious aspects of digital Self-Excited-Loops for SRF cavity control',
 'A Quantum Algorithm for Nonlinear Electromagnetic Fluid Dynamics via Koopman-von Neumann Linearization',
 'Rumor propagation on hypergraphs',
 'Anti-hyperuniform Critical States of Active Topological Defects',
 'Vortices and backflow in hydrodynamic heat transport',
 'Multiparticle quantum plasmonics: fundamentals and applications',
 'Strategic Development of a Hydrogen Supply Chain in Corsica: a Multi-criteria Analysis',
 'Paving the way to carbon neutrality: Evaluating the decarbonization of residential building electrification worldwide',
 'Operational entanglement of collective quantum modes at room temperature',
 'Social Laser Theory as a Natural Extension of Quantum-Like Modeling',
 'Emergence of nonclassical radiation in strongly laser-driven quantum systems',
 'Effects of oxidation and impurities in lithium surfaces on the emitting wall plasma sheath',
 'Evaluation of the upgraded 3-inch Hamamatsu photomultiplier for the KM3NeT Neutrino Telescope',
 'Strain-Gradient-Driven Decoupling of Thermal Suppression from Anisotropy in \\b{eta}-Ga2O3',
 'Acoustically control of integrated optical microrings: from photonic molecule to Mobius strip',
 'Slice Emittance Preservation and Focus Control in a Passive Plasma Lens',
 'Long-range evanescent coupling through photonic molecules',
 'One-shot acceleration of transient PDE solvers via online-learned preconditioners',
 'Theoretical Basis for Classifying Hyperuniform States of Two-Component Systems',
 'Forecast error diagnostics in neural weather models',
 'Energy-based interpretation of the dispersion coefficient of the constant phase element',
 'Characterizing the Role of Hind Flippers in Hydrodynamics of A Harbor Seal',
 'HydroFusion-LMF: Semi-Supervised Multi-Network Fusion with Large-Model Adaptation for Long-Term Daily Runoff Forecasting',
 'Metasurface-Based Dual-Basis Polarization Beam Splitter for efficient entanglement witnessing',
 'Photonic Crystal Microring Resonators on a Hybrid Silicon Nitride-on-Lithium Niobate Platform',
 'Heterogeneous networks for phase-sensitive engineering of optical disordered materials',
 'Star-shaped nanostructure-based multifunctional chiral metasurface for near-infrared wavelengths',
 'Supercontinuum generation from Topological Edge Supermodes in a short SSH Photonic Crystal Fiber',
 'Near-field perturbation of laser filament enabling simultaneous far-field THz diagnosis and broadband calculus processing',
 'Single $\\pi$-flux hosting topological defect modes in bilayer acoustic metamaterials',
 'Implementation of multiparticle quantum speed limits on observables',
 'Location matters: Exploring the effects of regional geographical and political characteristics on hydrogen pipeline costs globally',
 'Classical and quantum chaos in bean- and peanut-shaped billiards',
 'On void formation during the simulated tensile testing of polymer-filler particle composites',
 'A Platform for Evanescently Trapping Rb-87 Using Silicon Nitride Strip Waveguides Buried in Silica',
 'Surface Reduction Boosts Free Electron Concentration in MXene for Enhanced Photothermal Performance',
 'Orbit-orbit photonics: Harnessing vortex-trajectory interplay for light manipulation',
 'Information Wells and the Emergence of Primordial Black Holes in a Cyclic Quantum Universe',

In [20]:
#use this cell to see the titles of the papers of in each community (obtained using the Louvain method)
with open("./results/louvain_split", "rb") as file:
    subgraphs_list = pickle.load(file)

#use this variable to select the number of the community to consider
community = 5

titles_of_community = list(nx.get_node_attributes(subgraphs_list[community], "Title").values())

titles_of_community

['Dynamics of DNA-Templated Ultrafine Silver Nanowires Formation',
 'A Model Intercomparison Study of Mixed-Phase Clouds in a Laboratory Chamber',
 'Graphene Heterostructure-Based Non-Volatile Memory Devices with Top Floating Gate Programming',
 'On the transpositional relation for nonholonomic systems',
 'On the edge of complexity: The simplest not simple coupled mechanical system',
 'In-vivo femtonewton-sensing nanotribology of Tradescantia zebrina leaf cell inner surface using roll rotation detection',
 'Random Telegraph Noise of MIS and MIOS Silicon Nitride memristors at different resistance states',
 'Combining metal dewetting and lateral etching for the scalable top-down fabrication of GaN nanowire arrays with independently tunable diameter and spacing',
 'Discrete Action, Graph Evolution, and the Hierarchy of Symmetries: A Rigorous Construction of Temporal Layers $C1 \\to C2 \\to C3 \\to C4$',
 'Resonant states and nuclear dynamics in solid-state systems: the case of silicon-hydrogen bond dissociation',
 'Capacitive response of biological membranes',
 'Translational diffusion coefficients of membrane protein aggregates in free and supported lipid membranes',
 'Enhancing Reconstruction Capability of Wavelet Transform Amorphous Radial Distribution Function via Machine Learning Assisted Parameter Tuning',
 'Reaction kinetics of membrane receptors: a spatial modeling approach',
 'Nature of Hydrated Electron in Varied Solvation Environments',
 'An Investigation of Thermal Properties of Cu-Au Janus Nanoparticles',
 'The End of Hyperbolic Growth in Human Population and CO$_2$ Emissions',
 'On the Estimation of Centre of Mass in Periodic Systems',
 'Divisible and indivisible Stochastic-Quantum dynamics',
 'The influence of boundary conditions and interfacial slip on the time taken to achieve a nonequilibrium steady-state for highly confined flows',
 'Pressure-Induced Structural and Dielectric Changes in Liquid Water at Room Temperature',
 'Turbulence Impacted Wavefront Corrections Using Beam Modulation Technique',
 'Is Gravity Truly Balanced? A Historical-Critical Journey Through the Equivalence Principle and the Genesis of Spacetime Geometry',
 'Efficient Grand Canonical Global Optimization with On-the-fly-trained Machine-learning Interatomic Potentials',
 'Kullback-Leibler Divergence as a Measure of Irreversible Information Loss Near Black Hole Horizons',
 "Evolution of human cognition required Einstein's gravitational waves",
 'What defines stationarity in space plasmas',
 'The Hungry Daemon: An energy-harvesting active particle must obey the Second Law of Thermodynamics',
 'CondensNet: Enabling stable long-term climate simulations via hybrid deep learning models with adaptive physical constraints',
 'Simulations of dielectric permittivity of water by Machine Learned Potentials with long-range Coulombic interactions',
 'The Moving Beam Diffraction Geometry: the DIAD Application of a Diffraction Scanning-Probe',
 'Insights into new mechanosensitive behaviors of G protein-coupled receptors',
 'Material-Driven Optimization of Transmon Qubits for Scalable and Efficient Quantum Architectures',
 'Non-equilibrium distribution function in ultra-fast processes',
 'Many-Body Coarse-Grained Molecular Dynamics with the Atomic Cluster Expansion',
 'Laser transfer and retrieval via nanophotonic supercontinuum process',
 'UP-dROM : Uncertainty-Aware and Parametrised dynamic Reduced-Order Model, application to unsteady flows',
 'A generalised framework for phase field-based modelling of coupled problems: application to thermo-mechanical fracture, hydraulic fracture, hydrogen embrittlement and corrosion',
 "The Transparent Earth: A Multimodal Foundation Model for the Earth's Subsurface",
 'Collective communication in a transparent world: Phase transitions in a many-body Potts model and social-quantum duality',
 'Computing leaky waves in semi-analytical waveguide models by exponential residual relaxation',
 'Conventional Scintillation Statistics with Turbulence Impacted Coupled Dipole Oscillation',
 'Optimal velocity fields for instantaneous magnetic field growth',
 'Resummed Distribution Functions: Making Perturbation Theory Positive and Normalized',
 'A universal preprocessing algorithm of average kernel method with Gauss-Laguerre quadrature for double integrals',
 'Interpretable inverse design of optical multilayer thin films based on extended neural adjoint and regression activation mapping',
 'Output correction factors in a 1.5 T magnetic field determined at the central axis and at the lateral dose maximum for five detectors using alanine',
 'A Novel Nonlinear IP$_3$R State Transition Model and Calcium Oscillation',
 'From Symmetry to Supersymmetry to Supergravity',
 'What day is the peak of birth in France?',
 'Formation of external particle jets on a spherical particle bed subjected to strong explosive loading',
 'An operator approach to the analysis of electromagnetic wave propagation in dispersive media. Part 2: transmission problems',
 'Nonequilibrium Work Fluctuations in Force-induced Melting of a Short B-DNA',
 'Computational study of vertical-axis MHK turbines using a coupled flow-sediment-turbine modeling approach',
 'Boosting the Self-driven Properties of 2D Photodetectors through Synergistic Asymmetrical Effects',
 'Instance-Wise Adaptive Sampling for Dataset Construction in Approximating Inverse Problem Solutions',
 'Machine learning prediction of a chemical reaction over 8 decades of energy',
 'Mesoscale particle-based simulations of flow in expansion-contraction microchannels at low Reynolds number',
 'Physics-informed coherent motions to predict Lagrangian trajectories',
 'Fine-Tuning Hydrophilic-Hydrophobic Balance in Stimuli-Responsive PEGPNIPAM Micelles for Controlled Drug Delivery',
 'Utilizando o captador de guitarra como sensor: Construindo um kit para abordar a Lei de Faraday em sala de aula',
 'Unraveling superradiance: Entanglement and mutual information in collective decay',
 "Atmospheric dynamics of IR-active particles released from Mars' surface",
 'Composable and adaptive design of machine learning interatomic potentials guided by Fisher-information analysis',
 'An atom chip interferometer',
 'Ferroelectricity in dipolar liquids: the role of annealed positional disorder',
 'Formation of a Tungsten Co-deposition Layer with Microparticles Using Pulsed Laser Deposition',
 'Influx of Bay of Bengal waters and stirring trends in the Arabian Sea based on satellite altimetry',
 'Scalable registration of single quantum emitters within solid immersion lenses through femtosecond laser writing',
 'Silicon nitride on-chip C-band spontaneous emission generation based on lanthanide doped microparticles',
 'Three dimensional He+ pickup ion velocity distribution functions observed with STEREO-A PLASTIC',
 'Anti-localization of non-stationary quasi-waves in a strongly nonlinear $\\beta$-FPUT chain',
 "The effect of finite duration sources on modes and generalization of the d'Alembert solution",
 'A Unified Framework from Boltzmann Transport to Proton Treatment Planning',
 'Dynamic correlations in a polar fluid: confronting stochastic density functional theory to simulations',
 'A Fast, Parallelized, GPU-Accelerated Photochemical Model, XODIAC, with Built-in Equilibrium Chemistry and Multiple Chemical Networks for Exoplanetary Atmospheres',
 'New insights into the cavitation erosion by bubble collapse at moderate stand-off distances',
 'A general model for frictional contacts in colloidal systems',
 'Unifying Kappa Distribution Models for Non-Equilibrium Space Plasmas: A Superstatistical Approach Based on Moments',
 "Reconstructing the Sun's Alfv\\'en surface and wind braking torque with Parker Solar Probe",
 'Cosmic Rays on Galaxy Scales: Progress and Pitfalls for CR-MHD Dynamical Models',
 'Enhancing optical lattice clock coherence times with erasure conversion',
 'Lithographic integration of TES microcalorimeters with SQUID multiplexer circuits for large format spectrometers',
 'Lithographically Defined Si$_3$N$_4$ Torsional Pendulum',
 "Gravitational friction from d'Alembert's principle",
 'Predicting random close packing of binary hard-disk mixtures via third-virial-based parameters',
 'State Characterisation of Self-Directed Channel Memristive Devices',
 'Interference Fringe Mitigation in Short-Delay Self-Heterodyne Laser Phase Noise Measurements',
 'Non-adiabatically driven quantum interference effects in the ultracold K + KRb $\\longrightarrow$ Rb + K$_{2}$ chemical reaction',
 'Hybrid Integration of InGaN Lasers in a Foundry-Fabricated Visible-Light Photonics Platform',
 'Why did the dark matter hypothesis supersede modified gravity in the 1980s?',
 'pylimer-tools: A Python Package for Generating and Analyzing Bead-Spring Polymer Networks',
 'Thermal Resilience of Suspended Thin-Film Lithium Niobate Acoustic Resonators up to 550 {\\deg}C',
 'Relativistic recoil as a key to the fine-structure puzzle in muonic $^{90}\\text{Zr}$',
 'Fast-wave slow-wave spectral deferred correction methods applied to the compressible Euler equations',
 'Phase-Field Modeling and Energy-Stable Schemes for Osmotic Flow through Semi-Permeable',
 'Bell Correlations from Prepared Coherence in Entangled Dirac Wavepackets',
 'Impact of Stochastic Acceleration on the Pickup Proton Distribution and ENA Fluxes in the Heliosphere',
 'What is a chemostat? Insights from hybrid dynamics and stochastic thermodynamics',
 'Foundations of magnetohydrodynamics',
 'Prospects for Ultralow-Mass Nuclear Magnetic Resonance using Spin Defects in Hexagonal Boron Nitride',
 'Local extraction of three-dimensional magnetic reconnection X-lines',
 'An Explainable AI Model for Binary LJ Fluids',
 'Ferroelectric Al$_{1-x}$B$_x$N sputtered thin films on n-type Si bottom electrodes',
 'Fast simulation of fermions with reconfigurable qubits',
 'Universal gates for a metastable qubit in strontium-88',
 'Toda lattice formed in nonequilibrium steady states of SWCNT',
 'The Quantum Method of Planes -- Local Pressure Definitions for Machine Learning Potentials',
 'Ionization Rate of Interstellar Neutral Helium from New Horizons/SWAP Observations',
 'Towards a format for describing networks / 1. Networks and knowledge graphs',
 'Probing and modeling cell-cell communication in 2D biomimetic tissues',
 'Understanding the IBEX ribbon using the kinetic model of pickup proton transport in a scatter-free limit',
 'ExPUFFIN: Thermodynamic Consistent Viscosity Prediction in an Extended Path-Unifying Feed-Forward Interfaced Network',
 'Interplay of asymmetry and fragmentation in the many-body tunneling dynamics of two-dimensional bosonic Josephson junctions',
 'Information thermodynamics of cellular ion pumps',
 'Influence of ion motion in a resonantly driven wakefield accelerator',
 'Impact of impurities on leakage current induced by High-Energy Density Pulsed Laser Annealing in Si diodes',
 'First non-zero measurement of a nuclear electric dipole moment',
 'The Stationary Point: A New Method for Solar Wind Speed Measurements from a Moving Vantage Point',
 'Atomic-Scale Insights into the Switching Mechanisms of RRAM Devices',
 'Electrochemical response of biological membranes to localized currents and external electric fields',
 'Membrane-Associated Self-Assembly for Cellular Decision Making',
 'Silicon nitride resistance switching MIS cells doped with silicon atoms',
 'SiNx RRAMs performance with different stoichiometries',
 'Breakdown characteristics of SiNx with different stoichiometries for resistive memories',
 'A Geometric Foundation for the Universal Laws of Turbulence',
 'Resistance Switching Properties of Stoichiometric and Nitrogen Implanted Silicon Nitride Nanolayers on N and P-Type Si Substrates',
 '400-Gbps/$\\lambda$ Ultrafast Silicon Microring Modulator for Scalable Optical Compute Interconnects',
 'Measuring optical force with a torsion pendulum: a platform for independent student experimentation',
 'Alexander Dalgarno and the development of astrochemistry',
 'Memory effects in wave-induced microplastic transport',
 'Ultrafast manipulation of magnetic skyrmions by microwave fields',
 'Study of arbitrarily low shear rate rheology using dissipative particle dynamics',
 'Stochastic Norton dynamics: An alternative approach for the computation of transport coefficients in dissipative particle dynamics',
 'Kappa distributions in the framework of superstatistics',
 'Quantum Monte Carlo in Classical Phase Space with the Wigner-Kirkwood Commutation Function. Results for the Saturation Liquid Density of $^4$He',
 'Efficient algorithms to solve atom reconfiguration problems. III. The bird and batching algorithms and other parallel implementations on GPUs',
 'Deterministic single-photon source with on-chip 5.6 GHz acoustic clock',
 'Radio Frequency from Optical with Instabilities below $10^{-15}$- Generation and Measurement',
 'The Simply Uninformed Thermodynamics of Erasure',
 'Robust Kirkwood-Buff inversion in complex mixtures via reciprocal-space methods',
 'Noise-induced Extreme Events in Hodgkin-Huxley Neural Networks',
 'Modeling Plant Action Potentials under Photoperiod Stress via Hodgkin-Huxley Dynamics',
 'Normal form computation of nonlinear dispersion relationship for locally resonant metamaterial',
 "A Hybrid Analytical Framework for Asymmetric Pressure and Boundary Layer Wind Simulation in Nor'easters",
 'Is the Goldman-Hodgkin-Katz equation universally true?',
 'Exceptional broadband absorption of nanoporous gold explained by plasmonic resonances at dangling ligaments',
 '300 mm Wafer-Scale SiN Platform for Broadband Soliton Microcombs Compatible with Alkali Atomic References',
 'High-fidelity entanglement and coherent multi-qubit mapping in an atom array',
 "Capturing the Demon in Szilard's Engine",
 'On the anisotropic velocity distribution of newborn pickup ions in the heliosheath',
 'Logical qubits with erasure conversion using metastable neutral atoms',
 "The Demon Hidden Behind Life's Ultra-Energy-Efficient Information Processing -- Demonstrated by Biological Molecular Motors",
 "Reconstruction of the Bacterial Flagellar Motor's Energy Landscape, Viscous Load, and Torque Generation Across Diffusion Regimes",
 'Photon emission gain in Er doped Si light emitting diodes by impact excitation',
 'Bridging Statistical Scattering and Aberration Theory: Ray Deflection Function -- I: Theoretical Framework',
 'Coarse-grained entropy balance of the Szilard engine',
 'Bridging Statistical Scattering and Aberration Theory: Ray Deflection Function -- II: Numerical Validation',
 'Leveraging Qubit Loss Detection in Fault Tolerant Quantum Algorithms',
 'Weak-Strong Uniqueness and Extreme Wall Events at High Reynolds Number',
 'The Role of Tunneling Oxide in the Low Frequency Noise of Multi-level Silicon Nitride ReRAMs',
 'Ideometrics: The Science of Generating, Evaluating and Prioritising Ideas',
 'Regional chemical potential analysis for material surfaces',
 'Finite-size effects of the excess entropy computed from integrating the radial distribution function',
 'Analogue simulation of quantum gravity black hole models in a dc-SQUID array',
 'Pumping and Steady Streaming driven by Two-Frequency Oscillations of a Cylinder',
 'On the transmission of texts: written cultures as complex systems',
 'Quantum coherence and negative quasi probabilities in a contextual three-path interferometer',
 'Rain from Solar Scattering',
 'Asymmetrical Filtering Impairments Mitigation for Digital- Subcarrier-Multiplexing Transmissions Enabled by Multiplication-free K-State Reserved Complex MLSE',
 'Information Wells and the Emergence of Primordial Black Holes in a Cyclic Quantum Universe',
 'Disparity-in-Differences: Extracting Hierarchical Backbones of Weighted Directed Networks',
 'Modeling of van-der-Meer scan at NICA',
 'Effect of Al2O3 on the operation of SiNX-based MIS RRAMs',
 'Encoding classical data into the squeezing of noisy-states for plasmonic communication',
 'Effect of Silicon Atom Doping in SiNx Resistive Switching Films',
 'Tracking the creation of single photon emitters in AlN by implantation and annealing',
 'Spontaneous Raman scattering out of a metastable atomic qubit',
 'Split-gasket approach to the integration of electrical leads into diamond anvil cells',
 'Origin of compact exoplanetary systems during disk infall',
 'Soft quantum back reaction to the Hubble tension: a smeared-out early time cosmological energy density',
 'Transmembrane transport of polymer brush-grafted nanoparticles into giant vesicles',
 'Rapid Single-Cell Measurement of Transient Transmembrane Water Flow under Osmotic Gradient',
 'A microstructural rheological model for transient creep in polycrystalline ice',
 'Quantum Gambling: Best-Arm Strategies for Generator Selection in Adaptive Variational Algorithms',
 'Magnetohydrodynamic/Kinetic Modeling of the Interaction between the Solar Wind and the Local Interstellar Medium with He$^+$, He$^{2+}$, and Pickup H$^+$ ions and H, He Atoms',
 'Progress in evaluating a possible electromagnetic interaction energy in a gravitational field',
 "Disentangling Brillouin's negentropy law of information and Landauer's law on data erasure",
 'Tailored Thin Films: Modulating Soft Photonics with Dynamically Tunable Large Area Microstructures via Controlled Thermal Processing',
 'Unconventional Materials for Light Dark Matter Detection',
 'Fine structure of phase diagram for social impact theory',
 'Scalable, Cloud-Based Simulations of Blood Flow and Targeted Drug Delivery in Retinal Capillaries',
 'Asymmetrical cavity design that bypasses mode mixings in axion haloscope experiments',
 "Maxwell's Demon Is Foiled by the Entropy Cost of Measurement, Not Erasure",
 'Water structuring at stacked graphene interfaces unveiled by machine-learning molecular dynamics',
 'Polydisperse collision kernels in droplet-laden turbulence with implications for rain formation',
 'The equilibrium distribution function for strongly nonlinear systems',
 'Self-organized criticality driven by droplet influx and random fusion',
 'Unified interface dipole theory for Fermi level pinning effect at metal-semiconductor contacts',
 'Plasmonic nanopore to monitor in-pore chemistry',
 "Hunting for Maxwell's Demon in the Wild",
 'Dynamics of reactive oxygen species produced by the COST microplasma jet',
 'How Convective Mass Flux Responds to Environmental Humidity',
 'Kullback-Leibler Potential for Non-Ergodic Replication Dynamics:An Information-Theoretic Second Law',
 'Impact of Outreach on Physics Student Development: Qualitative Results from a National Survey',
 'An ensemble of Gaussian fields with multifractal statistics for turbulence',
 'Formation and Regulation of Calcium Sparks on a Nonlinear Spatial Network of Ryanodine Receptors',
 'Symmetrical bipolar electrobending deformation in acceptor-doped piezoceramics',
 'A State-Space-View of Atom-Diatom Reactions Relevant to Rarefied Gas Flow',
 'Spiral defect chaos with intermittency increases mean termination time',
 'The viscoelastic rheology of transient diffusion creep',
 'Urban Planning in 3D with a Two-tier LUTI model',
 'A Pathway to Sub-meV Detection of the Dark Universe: Robust Electron Avalanche in the PN junction at 10 mK',
 'Unrepeated White Rabbit Time Synchronisation over a 300 km Optical Fibre Link',
 'New routes for PN destruction and formation in the ISM via neutral-neutral gas-phase reactions and an extended database for reactions involving phosphorus']

Analyzing the cathegory of papers in each community, we can immediately notice that there is no more one main cathegory for each community: the different cathegories are quite mixed in each community. It looks like the removal of high-entropy components makes it more easy to divide the network, but at the same time the recognition of different topics becomes more difficult. As we can also see from the list of titles in each community, even papers of very different topics are assigned to the same community.

In conclusion, removing high entropy components makes the division into communities easier, but the classification becomes worse. However, we only tried one value of threshold on entropy: maybe removing a lower number of components would give a classification even better than the one obtained keeping all the components.

An important remark is that we don't have any score telling how good is a classification: as already said in the original project, the only way to evaluate the classification performances would be to read each paper (or at least the title/abstract of each paper), and see if papers in the same community actually have a topic in common. Such kind of evaluation, however, requires a lot of time, and so it is very difficult to compare different classifications.